-- 코드를 입력하세요
SELECT A.AUTHOR_ID	
     , A.AUTHOR_NAME	
     , B.CATEGORY
     , SUM(B.PRICE * C.SALES) AS TOTAL_SALES
  FROM AUTHOR A
  JOIN
       BOOK B
    ON 
       A.AUTHOR_ID = B.AUTHOR_ID
  JOIN
       BOOK_SALES C
    ON
       B.BOOK_ID = C.BOOK_ID
  WHERE TO_CHAR(C.SALES_DATE, 'YYYY-MM') = '2022-01' 
  GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
  ORDER BY A.AUTHOR_ID, B.CATEGORY DESC
    