SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR( C.DAILY_FEE * 30 * (100 - DP.DISCOUNT_RATE) / 100 ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
  ON DP.CAR_TYPE = C.CAR_TYPE
 AND DP.DURATION_TYPE = '30일 이상'                 -- 30일 요금 가정
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  -- 11월과 겹치는 대여 이력이 '없는' 차량만: 대여 가능
  AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
        WHERE RH.CAR_ID = C.CAR_ID
          AND RH.START_DATE <= DATE '2022-11-30'
          AND RH.END_DATE   >= DATE '2022-11-01'
  )
  -- 30일 요금 범위: 50만 이상, 200만 미만
  AND FLOOR( C.DAILY_FEE * 30 * (100 - DP.DISCOUNT_RATE) / 100 )
        BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
