-- 코드를 입력하세요
SELECT  TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
      , to_number(to_char(sales_date, 'MM')) AS MONTH
      , GENDER
      , COUNT(DISTINCT A.USER_ID) AS USERS
  FROM  ONLINE_SALE A
  JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), to_number(to_char(sales_date, 'MM')), GENDER
ORDER BY YEAR, MONTH, GENDER;