-- 코드를 입력하세요
SELECT A.PRODUCT_ID	
     , A.PRODUCT_NAME	
     , SUM(PRICE * B.AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
  JOIN
        FOOD_ORDER B
    ON
        A.PRODUCT_ID = B.PRODUCT_ID
 WHERE  EXTRACT(MONTH FROM  PRODUCE_DATE) = 5
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
 ORDER BY SUM(PRICE * B.AMOUNT) DESC , A.PRODUCT_ID	