-- 코드를 입력하세요
SELECT RH.HISTORY_ID
     , ((RH.END_DATE - RH.START_DATE + 1) * CC.DAILY_FEE * (100 - NVL(DP.DISCOUNT_RATE, 0)) * 0.01) AS FEE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
  JOIN 
       CAR_RENTAL_COMPANY_CAR CC
    ON
       RH.CAR_ID = CC.CAR_ID
LEFT JOIN
       CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON
       DP.CAR_TYPE = CC.CAR_TYPE
   AND DP.DURATION_TYPE =(
        CASE 
            WHEN ((RH.END_DATE - RH.START_DATE+1) >= 90) THEN '90일 이상'
            WHEN ((RH.END_DATE - RH.START_DATE+1) >= 30) THEN '30일 이상'
            WHEN ((RH.END_DATE - RH.START_DATE+1) >= 7)  THEN '7일 이상'
        ELSE
           NULL
        END)
 WHERE CC.CAR_TYPE = '트럭'
 ORDER BY FEE DESC , RH.HISTORY_ID DESC
 
      