-- 코드를 입력하세요
SELECT A.APNT_NO	
     , C.PT_NAME	
     , C.PT_NO	
     , B.MCDP_CD
     , B.DR_NAME
     , A.APNT_YMD
  FROM APPOINTMENT A
  JOIN
    DOCTOR B
  ON B.DR_ID = A.MDDR_ID
  JOIN
    PATIENT C
  ON
    C.PT_NO = A.PT_NO
WHERE A.APNT_CNCL_YN = 'N'
  AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
  ORDER BY APNT_YMD