-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER,  TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH 
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH , 'MM') = 3 AND TLNO is not null AND GENDER = 'W'
ORDER BY member_id ASC