-- 코드를 입력하세요
SELECT USER_ID	
     , NICKNAME	
     , SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE A.STATUS = 'DONE'
  AND A.WRITER_ID = B.USER_ID
GROUP BY USER_ID, NICKNAME
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES