-- 코드를 입력하세요
SELECT A.CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
  JOIN 
       CAR_RENTAL_COMPANY_CAR  B
    ON A.CAR_ID = B.CAR_ID
   AND CAR_TYPE = '세단'
 WHERE (EXTRACT(MONTH FROM START_DATE) = '10')
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC



